# GitHub Actions workflow to build and deploy a Next.js site to GitHub Pages

name: Deploy to GitHub Pages

on:
  # Run on pushes to the main branch
  push:
    branches: [ main ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: List files in the repository
      # This is a debug step to see the file structure.
      # It will help verify the location of package-lock.json.
      run: ls -R

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        # Pointing to the package-lock.json inside the project subdirectory.
        cache-dependency-path: package-lock.json
        
    - name: Install dependencies
      # Set the working directory for this and subsequent steps.
      working-directory: .
      run: npm ci
        
    - name: Build Next.js app
      working-directory: .
      run: npm run build
      
    - name: Add nojekyll file
      run: touch ./out/.nojekyll
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # The path should be relative to the repository root, so we point to the build output inside the subdirectory.
        path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Only deploy when the push is to the 'main' branch
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
